name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Extract name with 4 characters
      id: extract
      run: |
        # Get the repository name from the GitHub context
        REPO_NAME="${{ github.repository }}"  # This will dynamically get the repository name
        
        # Extract the parts of the repository name
        IFS='/' read -r -a PARTS <<< "$REPO_NAME"
        REPO_NAME=${PARTS[1]} # Use the second part of the repository name (ignoring owner)
        
        echo "Extracted repository name: $REPO_NAME"
    
        # Find the 4 character name
        FOUR_CHAR_NAME=$(echo "$REPO_NAME" | tr '-' '\n' | grep -E '^[a-zA-Z0-9]{4}$')
         FOUR_CHAR_NAME=${FOUR_CHAR_NAME:-$(echo "$REPO_NAME" | tr '-' '\n' | grep -E '^AWB$')}
    
         if [ -n "$FOUR_CHAR_NAME" ]; then
           if [[ "$FOUR_CHAR_NAME" == "AWB" ]]; then
             echo "'AWB' found in the repository name."
           else
             echo "4 character name found: $FOUR_CHAR_NAME"
           fi
         else
           echo "Neither a 4 character name nor 'AWB' was found."
           exit 1 
         fi
         
         # Set the output to use in later steps
         echo "FOUR_CHAR_NAME=$FOUR_CHAR_NAME" >> $GITHUB_ENV
  
    - name: List exported environment variables
      run: |
        for var in $(compgen -v | grep '^dist'); do
          echo "$var=${!var}"
        done
      
    - name: Extract paths from environment variables
      run: |
       for var in $(compgen -v | grep '^dist3'); do
         path=${!var}
         echo "Extracted path: $path"
       done