name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set repository name
      id: repo-name
      run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
   
    #- name: Use repository name in path
    #  run: echo "The repository name is ${{ env.REPO_NAME }} and it will be used in the path /path/to/${{ env.REPO_NAME }}"