name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Extrair nome nome do centro de custo
      id: short-repo-name
      run: echo "SHORT_REPO_NAME=$(basename $GITHUB_REPOSITORY | cut -c1-4)" >> $GITHUB_ENV
      shell: bash
    
    - name: Find and export properties
      shell: bash
      run: |
       # Encontra todos os arquivos .properties e processa cada um
       for file in $(find . -name "*.properties"); do
         # Extrai todas as propriedades e exporta para o ambiente GitHub
         while IFS='=' read -r key value; do
         if [ -n "$key" ] && [ -n "$value" ]; then
           echo "${key}=${value}" >> $GITHUB_ENV
         fi
         done < "$file"
       done
       
    
