name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extrair nome nome do centro de custo
      id: short-repo-name
      run: echo "SHORT_REPO_NAME=$(basename $GITHUB_REPOSITORY | cut -c1-4)" >> $GITHUB_ENV
      shell: bash

    - name: List and display properties file content
      run: |
        find . -name "*.properties" -exec cat {} \;
      shell: bash
     

