name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extrair nome do centro de custo
      id: short-repo-name
      run: echo "SHORT_REPO_NAME=$(basename $GITHUB_REPOSITORY | cut -c1-4)" >> $GITHUB_ENV
      shell: bash
    - name: Find, export, and store file paths
      shell: bash
      run: |
        # Inicializa a variável FILE_PATHS para armazenar os caminhos dos arquivos
        FILE_PATHS=""
    
        # Encontra todos os arquivos .properties e processa cada um
        for file in $(find . -name "*.properties"); do
          # Adiciona o caminho do arquivo à variável FILE_PATHS
          FILE_PATHS="$FILE_PATHS $file"
          
          # Extrai todas as propriedades e exporta para o ambiente GitHub
          while IFS='=' read -r key value; do
            if [ -n "$key" ] && [ -n "$value" ]; then
              echo "Exporting property: ${key}=${value}"
              echo "${key}=${value}" >> $GITHUB_ENV
            fi
          done < "$file"
        done
    
        # Exporta a variável FILE_PATHS com todos os caminhos
        echo "FILE_PATHS=$FILE_PATHS" >> $GITHUB_ENV
        echo "Stored file paths: $FILE_PATHS" # Exibe os caminhos armazenados
    
    - name: Combine and display extracted name and properties
      shell: bash
      run: |
       # Combine the extracted short repo name with properties
       combined_output="Centro de Custo: $SHORT_REPO_NAME"
       
       # Append all properties to the combined output
       for file in $(find . -name "*.properties"); do
         while IFS='=' read -r key value; do
         if [ -n "$key" ] && [ -n "$value" ]; then
           combined_output+="\n${key}=${value}"
         fi
         done < "$file"
       done
       
       # Display the combined output
       echo -e "$combined_output"
    
