name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extrair nome do centro de custo
      id: short-repo-name
      run: echo "SHORT_REPO_NAME=$(basename $GITHUB_REPOSITORY | cut -c1-4)" >> $GITHUB_ENV
      shell: bash
    
    - name: Find, export, and store file paths dynamically
      shell: bash
      run: |
        # Inicializa o contador
        counter=1
        
        # Encontra todos os arquivos .properties e processa cada um
        for file in $(find . -name "*.properties"); do
          # Define uma variável dinâmica distN onde N é o valor do contador
          var_name="dist${counter}"
          
          # Exporta o caminho do arquivo para uma variável com o nome dinâmico
          echo "${var_name}=$file" >> $GITHUB_ENV
          echo "Exporting ${var_name} with value: $file"
          
          # Incrementa o contador
          counter=$((counter + 1))
          
          # Extrai todas as propriedades e exporta para o ambiente GitHub
          while IFS='=' read -r key value; do
            if [ -n "$key" ] && [ -n "$value" ]; then
              echo "Exporting property: ${key}=${value}"
              echo "${key}=${value}" >> $GITHUB_ENV
            fi
          done < "$file"
        done
        
        echo "All file paths have been exported."
    
    - name: Use dist2 in another action
      run: |
        echo "Using dist2: ${{ env.dist2 }}"
    

    #- name: Combine and display extracted name and properties
    #  shell: bash
    #  run: |
    #   # Combine the extracted short repo name with properties
    #   combined_output="Centro de Custo: $SHORT_REPO_NAME"
    #   
    #   # Append all properties to the combined output
    #   for file in $(find . -name "*.properties"); do
    #     while IFS='=' read -r key value; do
    #     if [ -n "$key" ] && [ -n "$value" ]; then
    #       combined_output+="\n${key}=${value}"
    #     fi
    #     done < "$file"
    #   done
    #   
    #   # Display the combined output
    #   echo -e "$combined_output"
    #
