name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Checar name centro de Custo
      id: checar_nome
      run: |
        REPO_NAME="${{ github.repository }}"  # This will dynamically get the repository name
        
        # Extract the parts of the repository name
        IFS='/' read -r -a PARTS <<< "$REPO_NAME"
        REPO_NAME=${PARTS[1]} # Use the second part of the repository name (ignoring owner)

        echo "Extracted repository name: $REPO_NAME"
        
        if [[ ${#REPO_NAME} -eq 4 ]]; then
          FOUR_CHAR_NAME=$(echo "$REPO_NAME" | tr '-' '\n' | grep -E '^[a-zA-Z0-9]{4}$')
          echo "Nome Centro de Custo: $FOUR_CHAR_NAME"
          NOME_ENCONTRADO=$FOUR_CHAR_NAME
        fi
        
        if [[ -z "$NOME_ENCONTRADO" && "$REPO_NAME" == *"AWB"* ]]; then
           AWB_PART=$(echo $REPO_NAME | grep -o 'AWB[^/]*')
           echo "Nome contendo 'AWB' encontrado: $AWB_PART"
           NOME_ENCONTRADO=$AWB_PART
        fi

    

    - name: Checar pastas e arquivos
      id: checar_arquivos
      run: |
          NOME_ENCONTRADO=""
          ARQUIVO_ENCONTRADO=""

          # Procurar por pastas com 4 caracteres
          for dir in */; do
            dir_name=$(basename "$dir")
            if [[ ${#dir_name} -eq 4 ]]; then
              echo "Pasta com 4 caracteres encontrada: $dir_name"
              NOME_ENCONTRADO=$dir_name
              if [[ -f "$dir_name"/*.properties ]]; then
                ARQUIVO_ENCONTRADO=$(ls "$dir_name"/*.properties)
                echo "Pasta com 4 caracteres encontrada: $ARQUIVO_ENCONTRADO"
                break
              fi
            fi
          done

          # Procurar por pastas contendo 'AWB' se não encontrou anteriormente
          if [[ -z "$ARQUIVO_ENCONTRADO" ]]; then
            for dir in */; do
              dir_name=$(basename "$dir")
              if [[ "$dir_name" == *"AWB"* ]]; then
                echo "Pasta contendo 'AWB' encontrada: $dir_name"
                NOME_ENCONTRADO=$dir_name
                if [[ -f "$dir_name"/*.properties ]]; then
                  ARQUIVO_ENCONTRADO=$(ls "$dir_name"/*.properties)
                  break
                fi
              fi
            done
          fi

          # Definir variáveis globais
          echo "::set-output name=nome_encontrado::$NOME_ENCONTRADO"
          echo "::set-output name=arquivo_encontrado::$ARQUIVO_ENCONTRADO"

     