name: CI/CD Workflow

on:
  workflow_dispatch:
  push:
      branches:
        - main



jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Checar name centro de Custo
      id: checar_nome
      run: |
        REPO_NAME="${{ github.repository }}" 
        
        # Extract the parts of the repository name
        IFS='/' read -r -a PARTS <<< "$REPO_NAME"
        REPO_NAME=${PARTS[1]} 
        
        FOUR_CHAR_NAME=$(echo "$REPO_NAME" | tr '-' '\n' | grep -E '^[a-zA-Z0-9]{4}$')
        if [[ -n "$FOUR_CHAR_NAME" ]]; then
         echo "Nome Centro de Custo: $FOUR_CHAR_NAME"
         NOME_ENCONTRADO=$FOUR_CHAR_NAME
        fi
        
        if [[ -z "$NOME_ENCONTRADO" && "$REPO_NAME" == *"AWB"* ]]; then
           AWB_PART=$(echo $REPO_NAME | grep -o 'AWB[^/]*')
           echo "Nome contendo 'AWB' encontrado: $AWB_PART"
           NOME_ENCONTRADO=$AWB_PART
        fi

        if [[ -n "$NOME_ENCONTRADO" ]]; then
          LOWERCASE_NAME=$(echo "$NOME_ENCONTRADO" | tr '[:upper:]' '[:lower:]')
          echo "Buscando arquivo properties no repositório com prefixo: $LOWERCASE_NAME"
          for FILE in $(find . -name "${LOWERCASE_NAME}-*.properties"); do
            echo "Arquivo encontrado: $FILE"
    
             while IFS='=' read -r key value; do
             if [[ $key == dist* ]]; then
                echo "Exporting property: ${key}=${value}"
               echo "${key}=${value}" >> $GITHUB_ENV
             fi
           done < "$FILE"
          done
      
          echo "All dist properties have been exported."
        else
         echo "Nenhum nome de centro de custo encontrado."
        fi

    - name: Modify specific property
      run: |
       KEY="dist3"
       NEW_VALUE="test-pis.properties"
       if grep -q "^${KEY}=" $GITHUB_ENV; then
           sed -i "s/^${KEY}=.*/${KEY}=${NEW_VALUE}/" $GITHUB_ENV
           echo "Valor de ${KEY} alterado para ${NEW_VALUE}"
       else
           echo "Chave ${KEY} não encontrada no GITHUB_ENV."
       fi

    - name: Display specific property
      run: |
        KEY="dis8"
        VALUE=$(grep "^${KEY}=" $GITHUB_ENV | cut -d'=' -f2)
        if [[ -n "$VALUE" ]]; then
            echo "Valor de ${KEY}: ${VALUE}"
        else
            echo "Chave ${KEY} não encontrada no GITHUB_ENV."
        fi

    