name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Extract name with 4 characters
      id: extract
      run: |
        # Get the repository name
        REPO_NAME=${{ github.repository }}

        # Extract the parts of the repository name
        IFS='/' read -r -a PARTS <<< "$REPO_NAME"
        REPO_NAME=${PARTS[1]} # Use the second part of the repository name (ignoring owner)

        # Find and print the 4 character name
        FOUR_CHAR_NAME=$(echo "$REPO_NAME" | tr '-' '\n' | grep -E '^[a-zA-Z0-9]{4}$')
        echo "4 character names found: $FOUR_CHAR_NAME"

        # Set the output to use in later steps
        echo "name=$FOUR_CHAR_NAME" >> $GITHUB_ENV
    
  
    - name: Find, export, and store file paths dynamically
      shell: bash
      run: |
        # Inicializa o contador
        counter=1
        
        # Encontra todos os arquivos .properties e processa cada um
        for file in $(find . -name "*.properties"); do
          # Define uma variável dinâmica distN onde N é o valor do contador
          var_name="dist${counter}"
          
          # Exporta o caminho do arquivo para uma variável com o nome dinâmico
          echo "${var_name}=$file" >> $GITHUB_ENV
          echo "Exporting ${var_name} with value: $file"
          
          # Incrementa o contador
          counter=$((counter + 1))
          
          # Extrai todas as propriedades e exporta para o ambiente GitHub
          while IFS='=' read -r key value; do
            if [ -n "$key" ] && [ -n "$value" ]; then
              echo "Exporting property: ${key}=${value}"
              echo "${key}=${value}" >> $GITHUB_ENV
            fi
          done < "$file"
        done
        
        echo "All file paths have been exported."
  
      
    - name: List exported environment variables
      run: |
        for var in $(compgen -v | grep '^dist'); do
          echo "$var=${!var}"
        done
      
    - name: Extract paths from environment variables
      run: |
       for var in $(compgen -v | grep '^dist'); do
         path=${!var}
         echo "Extracted path: $path"
       done